title: Asrar Faroq | KU Comp. Sci
description: Everything at KU
theme: just-the-docs

url: https://YOUR-USERNAME.github.io/YOUR-SITE-NAME

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/Asrarfarooq/KU
