title: Asrar Faroq | KU Comp. Sci
description: Everything at KU
theme: just-the-docs

url: https://YOUR-USERNAME.github.io/YOUR-SITE-NAME

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/Asrarfarooq/KU

# Enable or disable the side/mobile menu globally
# Nav menu can also be selectively enabled or disabled using page variables or the minimal layout
nav_enabled: true
# Color scheme supports "light" (default) and "dark"
color_scheme: dark
